# Generated by Django 3.2.6 on 2021-08-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abstract', models.TextField(max_length=1000)),
                ('year', models.IntegerField()),
                ('venue', models.CharField(max_length=50)),
                ('pdf', models.FileField(default=' ', upload_to='media/', verbose_name='Research Paper')),
                ('peerReview', models.FileField(default=' ', upload_to='media/', verbose_name='Proof of Peer Review')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
