# Generated by Django 3.2.6 on 2021-08-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(to='main.Paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='main.Author'),
        ),
    ]
