# Generated by Django 3.2.6 on 2021-08-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210820_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='main.Author')),
                ('papers', models.ManyToManyField(to='main.Paper')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
