# Generated by Django 3.2.6 on 2021-08-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_author_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='peerReview',
            field=models.FileField(blank=True, default=' ', upload_to='media/', verbose_name='Proof of Peer Review'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='researchGroup',
            field=models.ManyToManyField(blank=True, to='main.ResearchGroup'),
        ),
    ]
