# Generated by Django 3.2.6 on 2021-08-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210820_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='authors',
            field=models.ManyToManyField(blank=True, to='main.Author'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='papers',
            field=models.ManyToManyField(blank=True, to='main.Paper'),
        ),
    ]
