# Generated by Django 3.2.6 on 2021-08-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_paper_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='venue',
            field=models.CharField(max_length=300),
        ),
    ]
