# Generated by Django 3.2.6 on 2021-08-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_paper_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='paper',
            order_with_respect_to='year',
        ),
    ]
