# Generated by Django 3.2.6 on 2021-08-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210821_1258'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='paper',
            order_with_respect_to='authors',
        ),
    ]
