# Generated by Django 3.2.6 on 2021-08-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210821_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchgroup',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='researchgroup',
            name='papers',
        ),
    ]
