# Generated by Django 3.2.6 on 2021-08-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210821_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='researchGroup',
            field=models.ManyToManyField(blank=True, to='main.ResearchGroup'),
        ),
        migrations.AddField(
            model_name='paper',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
