# Generated by Django 3.2.6 on 2021-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_researchgroup_paper_research_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='research_group',
            field=models.ManyToManyField(to='main.ResearchGroup'),
        ),
    ]
