# Generated by Django 3.2.6 on 2021-08-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_paper_research_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='researchGroup',
        ),
        migrations.AddField(
            model_name='author',
            name='researchGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchgroup'),
        ),
    ]
