# Generated by Django 3.2.6 on 2021-08-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210821_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='research_group',
        ),
        migrations.AddField(
            model_name='paper',
            name='research_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchgroup'),
        ),
    ]
