# Generated by Django 3.2.6 on 2021-08-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210821_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='research_group',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
