# Generated by Django 3.2.6 on 2021-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_paper_research_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='research_group',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
