# Generated by Django 3.2.6 on 2021-08-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_paper_research_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(blank=True, to='main.Paper'),
        ),
    ]
