# Generated by Django 3.2.6 on 2021-08-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_paper_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='name',
            new_name='title',
        ),
    ]
