# Generated by Django 3.2.6 on 2021-09-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_author_papers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='title',
            new_name='name',
        ),
    ]
