# Generated by Django 3.2.6 on 2021-09-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_title_paper_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='paper',
            order_with_respect_to='authors',
        ),
    ]
