# Generated by Django 3.2.6 on 2021-09-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210907_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-year', 'authors__surname']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='paper',
            order_with_respect_to=None,
        ),
    ]
