# Generated by Django 3.2.6 on 2021-09-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210907_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(blank=True, to='main.Paper'),
        ),
    ]
