# Generated by Django 3.2.6 on 2021-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_author_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='papers',
        ),
    ]
