# Generated by Django 3.2.6 on 2021-09-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_author_papers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname'], 'permissions': (('can_add_author', 'can_modify_author'),)},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-year'], 'permissions': (('can_add_paper', 'can_modify_paper'),)},
        ),
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(to='main.Paper'),
        ),
    ]
