# Generated by Django 3.2.6 on 2021-10-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210930_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-year'], 'permissions': (('can_add_paper', 'Add paper'), ('can_modify_paper', 'Modify Paper'), ('peer_review', 'Peer Review'))},
        ),
    ]
