# Generated by Django 3.2.6 on 2021-10-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_paper_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname'], 'permissions': (('can_add_author', 'Add author'), ('can_modify_author', 'Modify author'))},
        ),
    ]
