# Generated by Django 3.2.6 on 2021-10-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-year', 'authors__surname'], 'permissions': (('can_add_paper', 'Add paper'), ('can_modify_paper', 'Modify Paper'), ('peer_review', 'Peer Review'))},
        ),
        migrations.AlterField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(blank=True, to='main.Paper'),
        ),
    ]
