# Generated by Django 3.2.6 on 2021-10-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20211004_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-year', 'authors__surname'], 'permissions': (('can_add_paper', 'Can add paper'), ('can_modify_paper', 'Modify Paper'), ('peer_review', 'Peer Review'))},
        ),
    ]
